### ISSUE TITLE
Question with the analysis

### ISSUE THREAD

**Issue by P-W-T** [ldenies/OMECA#2]
Hey, 

I am trying to use your OMECA to make some calculations. 
I can't get the CEA output-file to look like yours. 
I am using the online version. Are there some things that I need to watch out for?

**Comment by ldenies** [comment]
Hi there,

To obtain a similar output from the online CEA, you should:
* Pick "rocket" as the problem type
* Input the desired combustion pressure (just one in my case)
* Select the fuel
* Select the oxidizer
* Set the O/F ratio (just one value again)
* Set a range of subsonic and supersonic area ratios (the values I used are
listed at the top of the CEA output file if you want to copy those)
* Select both equilibrium and frozen, set NFZ to 2
* Run

**Comment by P-W-T** [comment]
Hey,

Thanks for the reply, I found the problem yesterday. The trick was using the locally installed version of CEA. 
I am still working out some details, but the work is very nice!
